import Head from 'next/head'
import Navbar from '@/Components/Navbar/Navbar';
import LandingPage from '@/Components/HomePage/LandingPage';
import { useEffect, useState } from 'react';


export default function Home() {

  const [hideNavbar, setHiddenNavbar] = useState(false);

  useEffect(() => {
    let prevScroll = window.scrollY;
    window.onscroll= () =>{
      let currScroll = window.scrollY;
      if(currScroll>prevScroll){
        setHiddenNavbar(true)
      }else{
        setHiddenNavbar(false)
      }
      prevScroll = currScroll
    } 
  }, [])
  

  return (
    <>
      <Head>
        <title>Adidas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`md:fixed md:h-40 w-screen transition-all ease-in duration-300 delay-300 ${hideNavbar?'-translate-y-44':''} `}>
        <Navbar />
      </div>
      <div className=' absolute translate-y-[120px] -z-20 w-screen'>
        <LandingPage />
      </div>
    </>
  )
}
